### ISSUE TITLE
Suggestion: reorganize and submodule

### ISSUE THREAD

**Issue by MineRobber9000** [modgethanc/modgelib#1]
An idea I just thought of: instead of copying the files to repositories that use them, you could put the python files in the root and use git submodules ([discussed here](https://git-scm.com/docs/git-submodule)) to include them. Whenever files get added to this repo (or if you fix bugs) you can run a simple git command to update the affected repos.

**Comment by modgethanc** [comment]
this is super low-priority for me since my internal process for dealing with these files is sufficient, but thanks for your suggestion!
